version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: hs_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthsync_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/healthsync/app
      - ./data:/healthsync/data
      - ./scripts:/healthsync/scripts
    environment:
      - DATABASE_URL=postgresql://hs_user:password@db:5432/healthsync_db

volumes:
  pgdata:
